### ISSUE TITLE
163邮箱报错了哦。

### ISSUE THREAD

**Issue by weitemi** [fzf404/GoWebHooks#5]
我按照配置规则填的信息。使用的授权码作为密码。我同样的参数用python是可以发送邮件的。所以咋们这个go肯定还是哪儿有点不对哦。

**Comment by fzf404** [comment]
端口填的多少

**Comment by weitemi** [comment]
端口是配置文件里面默认的25




&nbsp;
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fzf404/WebHooks"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月1日(星期三) 上午10:58
***@***.***&gt;;
抄送:&nbsp;" ***@***.******@***.***&gt;;
主题:&nbsp;Re: [fzf404/WebHooks] 163邮箱报错了哦。 (Issue #5)





 
端口填的多少

**Comment by fzf404** [comment]
可以贴一下配置吗，我这里用是正常的

**Comment by weitemi** [comment]
这里改了配置是不是需要重启？我没有重启




&nbsp;
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fzf404/WebHooks"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月1日(星期三) 中午11:02
***@***.***&gt;;
抄送:&nbsp;" ***@***.******@***.***&gt;;
主题:&nbsp;Re: [fzf404/WebHooks] 163邮箱报错了哦。 (Issue #5)





 
可以贴一下配置吗，我这里用是正常的

**Comment by weitemi** [comment]
应该是没有重启的原因。
